services:
    db:
        image: postgres:13-alpine
        ports:
        - "5432:5432"
        environment:
          POSTGRES_DB: tableTop
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        volumes:
          - ./db_test:/docker-entrypoint-initdb.d
        healthcheck:
          test: ["CMD", "pg_isready", "-U", "postgres"]
          interval: 5s
