name: App Build & Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-latest, windows-latest ]
          java: [ 11, 17 ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v2
          with:
            java-version: ${{ matrix.java }}
            distribution: 'adopt'
        - name: Build with Gradle
          run: ./gradlew build

    tests:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: 11
            distribution: 'adopt'
        - name: Run tests with Gradle
          run: ./gradlew test
