name: App Build & Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
      strategy:
        fail-fast: true
        matrix:
          os: [ ubuntu-latest ]
          java: [ 11, 17 ]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK ${{ matrix.java }}
          uses: actions/setup-java@v3
          with:
            java-version: ${{ matrix.java }}
            distribution:
            architecture: x64
        - name: Echo Data
          run: echo "Hello Java"

